simple_cms/config/routes.rb
Rails.application.routes.draw do
  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'

  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  get ':controller(/:action(/:id))'
  get 'demo/index'
  get 'demo/about'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

simple_cms/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

simple_cms/app/models/page.rb
class Page < ApplicationRecord
end

simple_cms/app/models/subject.rb
class Subject < ApplicationRecord
  validates :name, :position, :visible, presence: true
end

simple_cms/app/models/user.rb
class User < ApplicationRecord
end

simple_cms/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

simple_cms/app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout =false
  def index
    @array = [2,4,6,8,10,11]
    render('index')
  end

  def about
    render('about')
    @id = params['id']
    @page = params[:page]
    #redirect_to(:controller => 'demo', :action => 'index')
  end
end

simple_cms/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end

  def show
  end

  def new
  end

  def create

  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end

end

simple_cms/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  layout 'admin'

  def index
    @subjects = Subject.order('position ASC')
    @page_title = "All Subjects"
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
    @subject_count = Subject.count + 1
  end

  def create  
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:notice] = "Subject successfully created!"
      redirect_to(subjects_path)
    else
      @subject_count = Subject.count + 1
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
    @subject_count = Subject.count
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params_modified)
      flash[:notice] = "Subject updated successfully!"
      redirect_to(subjects_path(@subject))
    else
      @subject_count = Subject.count
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject #{@subject.name} deleted successfully!"
    redirect_to(subjects_path)
  end

  private
    def subject_params
      params.require(:subject).permit(:name, :visible, :position, :created_at)
    end

    def subject_params_modified
      params.require(:subject).permit(:name, :visible, :position, :updated_at)
    end
end

simple_cms/app/helpers/application_helper.rb
module ApplicationHelper
  def status_tag(boolean, options={})
    options[:true_text] ||= ''
    options[:false_text] ||= ''

    if boolean
      content_tag(:span, options[:true_text], :class => 'status true')
    else
      content_tag(:span,options[:false_text], :class => 'status false')
    end
  end
end

simple_cms/app/helpers/demo_helper.rb
module DemoHelper
end

simple_cms/app/helpers/pages_helper.rb
module PagesHelper
end

simple_cms/app/helpers/subjects_helper.rb
module SubjectsHelper
end

simple_cms/app/views/demo/about.html.erb
<h1>Hello on my second page</h1>


ID: <%@id%></br>
id: <%params[:id]%> </br>
page: <%@page%>

simple_cms/app/views/demo/index.html.erb
<h1>Hello World</h1>
<p>Find me in app/views/demo/index.html.erb</p>

<% @array.each do |i|%>
      <%= i%>
      </br>
  <%end %>


<%= link_to("Click here to go about part", {:action => 'about'})%>



<%= link_to('All subjects', subjects_path)%>

simple_cms/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple CMS <%= @page_title || "Admin Area"%></title>
    <%= stylesheet_link_tag('admin', :media => 'all')%>
    <style>
      span.status {display: block; width: 10px; height: 10px; margin: 0.25em auto; padding: 0; border: 1px solid #000000;}
      span.status.true {background: green; color: green;}
      span.status.false {background: red; color: red;}
    </style>
  </head>

  <body>
    <div id = "header">
      <h1>Simple CMS Admin</h1>
    </div>
    <div class="main">
      <% if !flash[:notice].blank? %>
        <div class="notice">
          <%= flash[:notice]%>
        </div>
      <%end%>
    </div> 
    <div id="content">
      <%= yield %>
    </div>
    <br>
    <div id="footer">
      <p style="text-align: center;">Copyright by Junaid</p>
    </div>
  </body>
</html>

simple_cms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple CMS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

simple_cms/app/views/pages/delete.html.erb
<h1>Pages#delete</h1>
<p>Find me in app/views/pages/delete.html.erb</p>

simple_cms/app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

simple_cms/app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

simple_cms/app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

simple_cms/app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

simple_cms/app/views/subjects/_form.html.erb
<table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name, required: true) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.select(:position, @subject_count..@subject_count) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.check_box(:visible, checked: "checked") %></td>
      </tr>
      <tr>
        <th>
          Publish DateTime
        </th>
        <td>
          <%= f.datetime_select(:created_at, default: DateTime.now, :order => [:month, :day, :year], ampm: true)%>
        </td>
      </tr>
</table>

simple_cms/app/views/subjects/delete.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>

  <%= form_for(@subject, :method => 'delete') do |f| %>

    <p> Are you sure you want to delete</p>
    <%= @subject.name%>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

simple_cms/app/views/subjects/edit.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="Subjects edit">
  <h2>Update Subject</h2>

  <%= form_for(@subject) do |f| %>

    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name, required: true) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.select(:position, 1..@subject_count) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.check_box(:visible) %></td>
      </tr>
      <tr>
        <th>
          Modify Publish DateTime
        </th>
        <td>
          <%= f.datetime_select(:updated_at, :order => [:month, :day, :year])%>
        </td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

  <% end %>
</div>

simple_cms/app/views/subjects/index.html.erb
<div class = "Subjects Index"> 
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path)%>

  <table class = "listing" summary = "subject list">
    <tr class = "header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      
      <th>Actions</th>

    </tr>

    <% @subjects.each do |sub|%>
    <tr>
      <td><%= sub.position%></td>
      <td><%= sub.name%></td>
      <td class="center"><%= status_tag(sub.visible) %></td>
      
      <td class="center">
        <%= link_to("Show", subject_path(sub), :class => 'action show')%>
        <%= link_to("Edit", edit_subject_path(sub), :class => 'action edit')%>
        <%= link_to("Delete", delete_subject_path(sub), :class => 'action delete')%>
      </td>
    </tr>
    <% end %>
  </table>
</div>

simple_cms/app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject, :url => subjects_path, :method => 'post') do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>
</div>

simple_cms/app/views/subjects/show.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= status_tag(@subject.visible) %></td>
    </tr>
    <tr>
      <th>Publish DateTime</th>
      <td><%= @subject.created_at.strftime("%m/%d/%Y %I:%M:%S %p") %></td>
    </tr>
    <tr>
      <th>Last Modification</th>
      <td><%= @subject.updated_at.strftime("%m/%d/%Y %I:%M:%S %p") %></td>
    </tr>
  </table>

</div>